on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.2'
      - run: flutter clean
      - run: flutter pub get
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.1"

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Building iOS release
        run: |
          flutter build ios --release

      - name: Clean xcodebuild
        run: |
          xcodebuild clean -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Build xArchive
        run: |
          xcodebuild archive -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath build-output/app.xcarchive

      - name: check ios folder
        run: cd ios && ls

      - name: create ExportOptions.plist
        run: |
          #!/bin/bash
          VERSION=2.12
          cat > ios/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.mi.flutter</key>
              <string>MI Flutter Demo</string>
            </dict>
            <key>CFBundlePackageType</key>
          	<string>APPL</string>
            <key>teamID</key>
            <string>7224G6JACN</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>compileBitcode</key>
            <true/>
            <key>method</key>
            <string>app-store</string>
          </dict>
          </plist>
          EOF


      - name: check >> ExportOptions.plist is present at ios
        run: cd ios && ls

      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: check >> ExportOptions.plist is present at ios
        run: cd build-output/ios && ls

      - name: collect ipa artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          # Path to the release files
          path: build-output/ios

      - name: delete extra elements except ipa from build-output/ios
        run: cd build-output/ios && ls && rm -R DistributionSummary.plist && rm -R ExportOptions.plist && rm -R Packaging.log

      - name: check for only ipa
        run: cd build-output/ios && ls

      - name: Push to Github Releases dashboard
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build-output/ios/github_actions.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

      - name: Validate the iPA File
        run: xcrun altool --validate-app -f build-output/ios/github_actions.ipa -t ios -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

      - name: Upload ipa to Testflight
        run: xcrun altool --upload-app -f build-output/ios/github_actions.ipa -t ios -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        env:
          APPLE_USER_NAME: ${{secrets.USERNAME}}
          APPLE_APP_SPECIFIC_PASSWORD: ${{secrets.PASSWORD}}